### ISSUE TITLE
Issue value not found

### ISSUE THREAD

**Issue by andrea-avanzi** [atlassian/gajira-comment#13]
Hi, I trying to use this action.
Here my setup
```
     - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.ref }}
     
     - name: Comment on issue
        uses: atlassian/gajira-comment@v2.0.2
        with:
          comment: mycomment
```

"Find in commit messages" works well, here job's log
```
Run atlassian/gajira-find-issue-key@master
Searching in string: 
 refs/heads/feat/LEAR-9/action
Detected issueKey: LEAR-9
Saving LEAR-9 to /home/runner/.jira.d/config.yml
Saving LEAR-9 to /home/runner/jira/config.yml
```

But on "Comment on issue" there is this error
```
Error: Jira API error
    at Jira.fetch (/home/runner/work/_actions/atlassian/gajira-comment/v2.0.2/dist/index.js:1:63248)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  req: {
    method: 'POST',
    body: '{"body":"mycomment"}',
    url: '***/rest/api/2/issue//comment'
```

seems that `url` is malformed because missing `issue-id`
