### ISSUE TITLE
Does not seem to be compatible with ADF (Atlassian Document Format) 

### ISSUE THREAD

**Issue by jledoux-sonergia** [atlassian/gajira-comment#42]
Hello @mboudreau 

Thank you for maintaining this repo !

I'm trying to pretty format JIRA comments, by masking ugly 1km long urls with titles for instance, but Atlassian REST API is not compatible with markdown format, so I've tried to format it with Atlassian Document Format, but it shows as raw JSON on Jira issues.

Here is a basic example of minified JSON string in ADF format, I've removed most of its content to make it readable in this issue:

```yml
- name: Comment on JIRA issue
  uses: atlassian/gajira-comment@v3
  with:
    issue: ${{ inputs.JIRA_CODE }}
    comment: |
      {"version":1,"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Ticket déployé sur l'environnement ${{ steps.string.outputs.uppercase }}:"}]}]}
```

Shows as:
![image](https://github.com/atlassian/gajira-comment/assets/84727313/bbd328f2-0fe7-4b59-8903-67e6dca9fc46)

Is there a way to format comments using either markdown or ADF ? Or Should it be a feature request ?
